export const publication = [
    {
      "Id": 15,
      "Year": 2023,
      "Authors": "H Lundquist, H Andersson, MS Chew, J Das, MV Turkina, A Welin",
      "Title": "The Olfactomedin-4-Defined Human Neutrophil Subsets Differ in Proteomic Profile in Healthy Individuals and Patients with Septic Shock",
      "Journal": "Journal of Innate Immunity",
      "Number": "15 (1), 351-364",
      "Citation": 2,
      "DOI": "https://doi.org/10.1159/000527649",
      "Link": "https://karger.com/jin/article/15/1/351/835496",
      "Abstract": "The specific granule glycoprotein olfactomedin-4 (Olfm4) marks a subset (1–70%) of human neutrophils and the Olfm4-high (Olfm4-H) proportion has been found to correlate with septic shock severity. The aim of this study was to decipher proteomic differences between the subsets in healthy individuals, hypothesizing that Olfm4-H neutrophils have a proteomic profile distinct from that of Olfm4 low (Olfm4-L) neutrophils. We then extended the investigation to septic shock. A novel protocol for the preparation of fixed, antibody-stained, and sorted neutrophils for LC-MS/MS was developed. In healthy individuals, 39 proteins showed increased abundance in Olfm4-H, including the small GTPases Rab3d and Rab11a. In Olfm4-L, 52 proteins including neutrophil defensin alpha 4, CXCR1, Rab3a, and S100-A7 were more abundant. The data suggest differences in important neutrophil proteins that might impact immunological processes. However, in vitro experiments revealed no apparent difference in the ability to control bacteria nor produce oxygen radicals. In subsets isolated from patients with septic shock, 24 proteins including cytochrome b-245 chaperone 1 had significantly higher abundance in Olfm4-H and 30 in Olfm4-L, including Fc receptor proteins. There was no correlation between Olfm4-H proportion and septic shock severity, but plasma Olfm4 concentration was elevated in septic shock. Thus, the Olfm4-H and Olfm4-L neutrophils have different proteomic profiles, but there was no evident functional significance of the differences in septic shock."
    },
    {
      "Id": 17,
      "Year": 2023,
      "Authors": "Shahin H, Abdallah S, Das J, He W, El-Serafi I, Steinvall I, Sjöberg F, Elmasry M, El-Serafi AT",
      "Title": "miRNome and Proteome Profiling of Human Keratinocytes and Adipose Derived Stem Cells Proposed miRNA-Mediated Regulations of Epidermal Growth Factor and Interleukin 1-Alpha",
      "Journal": "International Journal of Molecular Sciences",
      "Number": "24 (5), 4956",
      "Citation": 1,
      "DOI": "https://doi.org/10.3390/ijms24054956",
      "Abstract": "Wound healing is regulated by complex crosstalk between keratinocytes and other cell types, including stem cells. In this study, a 7-day direct co-culture model of human keratinocytes and adipose-derived stem cells (ADSCs) was proposed to study the interaction between the two cell types, in order to identify regulators of ADSCs differentiation toward the epidermal lineage. As major mediators of cell communication, miRNome and proteome profiles in cell lysates of cultured human keratinocytes and ADSCs were explored through experimental and computational analyses. GeneChip® miRNA microarray, identified 378 differentially expressed miRNAs; of these, 114 miRNAs were upregulated and 264 miRNAs were downregulated in keratinocytes. According to miRNA target prediction databases and the Expression Atlas database, 109 skin-related genes were obtained. Pathway enrichment analysis revealed 14 pathways including vesicle-mediated transport, signaling by interleukin, and others. Proteome profiling showed a significant upregulation of the epidermal growth factor (EGF) and Interleukin 1-alpha (IL-1α) compared to ADSCs. Integrated analysis through cross-matching the differentially expressed miRNA and proteins suggested two potential pathways for regulations of epidermal differentiation; the first is EGF-based through the downregulation of miR-485-5p and miR-6765-5p and/or the upregulation of miR-4459. The second is mediated by IL-1α overexpression through four isomers of miR-30-5p and miR-181a-5p." 
    },
    {
      "Id": 21,
      "Year": 2023,
      "Authors": "C Braian, L Karlsson, J Das, M Lerm",
      "Title": "Selected β-glucans act as immune-training agents by improving anti-mycobacterial activity in human macrophages-a pilot study.",
      "Journal": "Journal of Innate Immunity",
      "Number": "",
      "Citation": 0,
      "DOI": "https://doi.org/10.1159/000533873",
      "Abstract": "Epigenetic reprogramming of innate immune cells by β-glucan in a process called trained immunity, leads to an enhanced host response to a secondary infection. β-glucans are structural components of plants, algae, fungi and bacteria and thus recognized as non-self by human macrophages. We selected the β-glucans curdlan from Alcaligenes faecalis, WGP dispersible from Saccharomyces cerevisiae, and β-glucan-rich culture supernatant of Alternaria and investigated whether they could produce trained immunity effects leading to an increased control of virulent Mycobacterium tuberculosis. We observed a significant M. tuberculosis growth-reduction in macrophages trained with curdlan and Alternaria, which also correlated with increased IL-6 and IL-1β release. WGP dispersible-trained macrophages were stratified into'non responders' and'responders', according to their ability to control M. tuberculosis, with'responders' producing higher IL-6 levels. The addition of neutrophils to infected macrophage cultures further enhanced macrophage control of virulent M. tuberculosis, but not in a stimuli-dependent manner. Pathway enrichment analysis of DNA methylome data also highlighted hypomethylation of genes in pathways associated with signaling and cellular reorganization and motility, and'responders' to WGP-training were enriched in the interferon-gamma signaling pathway. This study adds evidence that certain β-glucans show promise as immune training agents."
    },
    {
      "Id": 22,
      "Year": 2023,
      "Authors": "D Verma, N Kasic, F Jeppsson, C Eding, M Lysiak, S Fekri, J Das, C Enerbäck",
      "Title": "815 Altered methylation of microRNA in the psoriatic epidermis highlights the Wnt pathway",
      "Journal": "Journal of Investigative Dermatology",
      "Number": "143 (5), S140",
      "Citation": 0,
      "DOI": "https://doi.org/10.1016/j.jid.2023.03.825",
      "Abstract": "Psoriasis is an immune-mediated skin disease driven by the interplay between genetic predisposition and environmental factors. Epigenetic modifications have been reported in psoriasis, but the methylation of miRNA-encoding genes (MIRs) has not previously been explored. Using reduced representation bisulfite sequencing, we performed exhaustive genome-wide methylation profiling of MIR in lesional, non-lesional and healthy epidermis. We identified substantial differential methylation in MIRs (DM-MIRs), of which 14 intersecting DM-MIRs clearly distinguished the three skin phenotypes. Network analysis of the miRNA-target genes demonstrated the striking enrichment of the Wnt signaling pathway, not only in the inflammatory state but also in disease susceptibility. The inhibition of miRNA led to a substantial modulation of the Wnt target genes. Mechanistically, we demonstrated that psoriasis-associated cytokines promoted the increased methylation of certain MIRs, with a corresponding decrease in RNA expression. Our findings add a new level of complexity to miRNA regulation in psoriasis and provide a proof of concept that a psoriatic micro-milieu may regulate miRNA transcription through a methylation-dependent mechanism."
    },
    {
      "Id": 23,
      "Year": 2023,
      "Authors": "M Volpe, J Das",
      "Title": "methylR: a graphical interface for comprehensive DNA methylation array data analysis",
      "Journal": "Bioinformatics",
      "Number": "39 (4), btad184",
      "Citation": 0,
      "DOI": "https://doi.org/10.1093/bioinformatics/btad184",
      "Abstract": "DNA methylation analysis using arrays is a widely used method in research and clinical studies to study Epigenetics. Although several packages have been published to incur the results, most of them require a deep computational knowledge to perform the analysis. To resolve the limitation and to offer an easily accessible solution for researchers, we developed methylR a graphical tool that can analyze not only the raw data but also performs different downstream analyses with a few mouse clicks. We used standard and established open-source published packages or pipelines in methylR. We evaluated a publicly available dataset and compared the published results with those obtained with our tool. We implemented eight downstream analysis modules that can perform multidimensional analyses to pathway enrichment. Although the main application is designed for Illumina DNA methylation array data analysis, we made the accessory modules suitable for other kinds of data analysis as well. Freely available at Github: https://github.com/JD2112/methylr; Webserver: https://methylr.research.liu.se."
    },
    {
      "Id": 24,
      "Year": 2023,
      "Authors": "D Verma, N Kasic, F Jeppsson, C Eding, M Lysiak, S Fekri, J Das, C Enerbäck",
      "Title": "Differential DNA methylation of miRNA-encoding genes in psoriatic epidermis highlights the Wnt pathway.",
      "Journal": "The Journal of Investigative Dermatology, S",
      "Number": "S0022-202X (23) 00104",
      "Citation": 0,
      "DOI": "https://doi.org/10.1016/j.jid.2023.01.031",
      "Abstract": "MicroRNAs (miRNAs) are short, single-stranded RNA molecules playing significant roles in the post-transcriptional regulation of gene expression. Approximately 250 miRNAs are aberrantly expressed in psoriatic skin (Hawkes et al., 2016), but a putative epigenetic mechanism underlying their dysregulation is hitherto unexplored. This study aimed to explore whether miRNAs are regulated by methylation in psoriatic epidermis."
    },
    {
      "Id": 11,
      "Year": 2022,
      "Authors": "J Huoman, S Sayyab, E Apostolou, L Karlsson, L Porcile, M Rizwan, S Sharma, J Das, A Rosén & M Lerm",
      "Title": "Epigenetic rewiring of pathways related to odour perception in immune cells exposed to SARS-CoV-2 in vivo and in vitro",
      "Journal": "Epigenetics",
      "Number": "17 (13), 1875-1891",
      "Citation": 4,
      "DOI": "https://doi.org/10.1080/15592294.2022.2089471",
      "Abstract": "A majority of SARS-CoV-2 recoverees develop only mild-to-moderate symptoms, while some remain completely asymptomatic. Although viruses, including SARS-CoV-2, may evade host immune responses by epigenetic mechanisms including DNA methylation, little is known about whether these modifications are important in defence against and healthy recovery from COVID-19 in the host. To this end, epigenome-wide DNA methylation patterns from COVID-19 convalescents were compared to uninfected controls from before and after the pandemic. Peripheral blood mononuclear cell (PBMC) DNA was extracted from uninfected controls, COVID-19 convalescents, and symptom-free individuals with SARS-CoV-2-specific T cell-responses, as well as from PBMCs stimulated in vitro with SARS-CoV-2. Subsequently, the Illumina MethylationEPIC 850K array was performed, and statistical/bioinformatic analyses comprised differential DNA methylation, pathway over-representation, and module identifica- tion analyses. Differential DNA methylation patterns distinguished COVID-19 convalescents from uninfected controls, with similar results in an experimental SARS-CoV-2 infection model. A SARS-CoV-2-induced module was identified in vivo, comprising 66 genes of which six (TP53, INS, HSPA4, SP1, ESR1, and FAS) were present in corresponding in vitro analyses. Over-representation analyses revealed involvement in Wnt, muscarinic acetylcholine receptor signalling, and gonadotropin-releasing hormone receptor pathways. Furthermore, numerous differentially methylated and network genes from both settings interacted with the SARS-CoV -2 interactome. Altered DNA methylation patterns of COVID-19 convalescents suggest recovery from mild-to-moderate SARS-CoV-2 infection leaves longstanding epigenetic traces. Both in vitro and in vivo exposure caused epigenetic modulation of pathways thataffect odour perception. Future studies should determine whether this reflects host-induced protective antiviral defense or targeted viral hijacking to evade host defence."
    },
    {
      "Id": 12,
      "Year": 2022,
      "Authors": "M Łysiak, J Das, A Malmström, P Söderkvist",
      "Title": "Methylation associated with long-or short-term survival in glioblastoma patients from the Nordic phase 3 trial",
      "Journal": "Frontiers in Genetics",
      "Number": "13, 934519",
      "Citation": 3,
      "DOI": "https://doi.org/10.3389/fgene.2022.934519",
      "Abstract": "Patients with glioblastoma (GBM) have a poor outcome, but even among patients receiving the same therapies and with good prognostic factors, one can find those with exceptionally short and long survival. From the Nordic trial, which randomized GBM patients of 60 years or older between two radiotherapy arms (60 Gy or 34 Gy) or temozolomide (TMZ), we selected 59 with good prognostic factors. These selected GBM patients were equally distributed according to treatment and MGMT promoter methylation status but had long or short survival. Methylation profiling with the Illumina Infinium Methylation EPIC BeadChip arrays was performed and utilized for methylation-based CNS tumor classification, and pathway enrichment analysis of differentially methylated CpG sites (DMCs), as well as calculation of epigenetic age acceleration with three different algorithms, to compare the long and short survival groups. Samples identified by the classifier as non-GBM IDH wildtype were excluded. DMCs between long- and short-term survivors were found in patients with methylated MGMT promoter treated with TMZ (123,510), those with unmethylated MGMT treated with 60Gy radiotherapy (4,086), and with methylated MGMT promoter treated with 34Gy radiotherapy (39,649). Long-term survivors with methylated MGMT promoter treated with TMZ exhibited hypermethylation of the Wnt signaling and the platelet activation, signaling, and aggregation pathways. The joint analysis of radiotherapy arms revealed 319 DMCs between long- and short-term survivors with unmethylated MGMT and none for samples with methylated MGMT promoter. An analysis comparing epigenetic age acceleration between patients with long- and short-term survival across all treatment arms showed a decreased epigenetic age acceleration for the latter. We identified DMCs for both TMZ and RT-treated patients and epigenetic age acceleration as a potential prognostic marker, but further systematic analysis of larger patient cohorts is necessary for confirmation of their prognostic and/or predictive properties."
    },
    {
      "Id": 18,
      "Year": 2022,
      "Authors": "I Pehrson, S Sayyab, J Das, N Idh, J Paues, M Méndez-Aranda, C Ugarte-Gil & M Lerm",
      "Title": "The spectrum of tuberculosis described as differential DNA methylation patterns in alveolar macrophages and alveolar T cells",
      "Journal": "Clinical Epigenetics",
      "Number": "14 (1), 1-12",
      "Citation": 1,
      "DOI": "https://doi.org/10.1186/s13148-022-01390-9",
      "Abstract": "Host innate immune cells have been identified as key players in the early eradication of Mycobacterium tuberculosis and in the maintenance of an anti-mycobacterial immune memory, which we and others have shown are induced through epigenetic reprogramming. Studies on human tuberculosis immunity are dominated by those using peripheral blood as surrogate markers for immunity. We aimed to investigate DNA methylation patterns in immune cells of the lung compartment by obtaining induced sputum from M. tuberculosis- exposed subjects including symptom-free subjects testing positively and negatively for latent tuberculosis as well as patients diagnosed with active tuberculosis. Alveolar macrophages and alveolar T cells were isolated from the collected sputum and DNA methylome analyses performed (Illumina Infinium Human Methylation 450k). Multidimensional scaling analysis revealed that DNA methylomes of cells from the tuberculosis-exposed subjects and controls appeared as separate clusters. The numerous genes that were differentially methylated between the groups were functionally connected and overlapped with previous findings of trained immunity and tuberculosis. In addition, analysis of the interferon-gamma release assay (IGRA) status of the subjects demonstrated that the IGRA status was reflected in the DNA methylome by a unique signature. This pilot study suggests that M. tuberculosis induces epigenetic reprogramming in immune cells of the lung compartment, reflected as a specific DNA methylation pattern. The DNA methylation signature emerging from the comparison of IGRA-negative and IGRA-positive subjects revealed a spectrum of signature strength with the TB patients grouping together at one end of the spectrum, both in alveolar macrophages and T cells. DNA methylation-based biosignatures could be considered for further development towards a clinically useful tool for determining tuberculosis infection status and the level of tuberculosis exposure."
    },
    {
      "Id": 4,
      "Year": 2021,
      "Authors": "L Karlsson, J Das, M Nilsson, A Tyrén, I Pehrson, N Idh, S Sayyab, J Paues, C Ugarte-Gil, M Méndez-Aranda, M Lerm",
      "Title": "A differential DNA methylome signature of pulmonary immune cells from individuals converting to latent tuberculosis infection",
      "Journal": "Scientific Reports",
      "Number": "11 (1), 19418",
      "Citation": 13,
      "DOI": "https://doi.org/10.1038/s41598-021-98542-3",
      "Abstract": "Tuberculosis (TB), caused by Mycobacterium tuberculosis, spreads via aerosols and the first encounter with the immune system is with the pulmonary-resident immune cells. The role of epigenetic regulations in the immune cells is emerging and we have previously shown that macrophages capacity to kill M. tuberculosis is reflected in the DNA methylome. The aim of this study was to investigate epigenetic modifications in alveolar macrophages and T cells in a cohort of medical students with an increased risk of TB exposure, longitudinally. DNA methylome analysis revealed that a unique DNA methylation profile was present in healthy subjects who later developed latent TB during the study. The profile was reflected in a different overall DNA methylation distribution as well as a distinct set of differentially methylated genes (DMGs). The DMGs were over-represented in pathways related to metabolic reprogramming of macrophages and T cell migration and IFN-γ production, pathways previously reported important in TB control. In conclusion, we identified a unique DNA methylation signature in individuals, with no peripheral immune response to M. tuberculosis antigen who later developed latent TB. Together the study suggests that the DNA methylation status of pulmonary immune cells can reveal who will develop latent TB infection."
    },
    {
      "Id": 5,
      "Year": 2021,
      "Authors": "A Singhania, P Dubelko, R Kuan, WD Chronister, K Muskat, J Das, EJ Phillips, SA Mallal, G Seumois, P Vijayanand, A Sette, M Lerm, B Peters, CL Arlehamn",
      "Title": "CD4+ CCR6+ T cells dominate the BCG-induced transcriptional signature",
      "Journal": "EBioMedicine",
      "Number": 74,
      "Citation": 11,
      "DOI": "https://doi.org/10.1016/j.ebiom.2021.103746",
      "Abstract": "The century-old Mycobacterium bovis Bacillus Calmette-Guerin (BCG) remains the only licensed vaccine against tuberculosis (TB). Despite this, there is still a lot to learn about the immune response induced by BCG, both in terms of phenotype and specificity. We investigated immune responses in adult individuals pre and 8 months post BCG vaccination. We specifically determined changes in gene expression, cell subset composition, DNA methylome, and the TCR repertoire induced in PBMCs and CD4 memory T cells associated with antigen stimulation by either BCG or a Mycobacterium tuberculosis (Mtb)-derived peptide pool. Following BCG vaccination, we observed increased frequencies of CCR6+ CD4 T cells, which includes both Th1* (CXCR3+CCR6+) and Th17 subsets, and mucosal associated invariant T cells (MAITs). A large number of immune response genes and pathways were upregulated post BCG vaccination with similar patterns observed in both PBMCs and memory CD4 T cells, thus suggesting a substantial role for CD4 T cells in the cellular response to BCG. These upregulated genes and associated pathways were also reflected in the DNA methylome. We described both qualitative and quantitative changes in the BCG-specific TCR repertoire post vaccination, and importantly found evidence for similar TCR repertoires across different subjects. The immune signatures defined herein can be used to track and further characterize immune responses induced by BCG, and can serve as reference for benchmarking novel vaccination strategies."
    },
    {
      "Id": 6,
      "Year": 2021,
      "Authors": "GH Zhu, M Azharuddin, R Islam, H Rahmoune, S Deb, U Kanji, J Das, J Osterrieth, P Aulakh, H Ibrahim-Hashi, R Manchanda, PH Nilsson, TE Mollnes, M Bhattacharyya, MM Islam, J Hinkula, NKH Slater, HK Patra",
      "Title": "Innate immune invisible ultrasmall gold nanoparticles—Framework for synthesis and evaluation",
      "Journal": "ACS applied materials & interfaces",
      "Number": "13 (20), 23410-23422",
      "Citation": 10,
      "DOI": "https://doi.org/10.1021/acsami.1c02834",
      "Abstract": "Nanomedicine is seen as a potential central player in the delivery of personalized medicine. Biocompatibility issues of nanoparticles have largely been resolved over the past decade. Despite their tremendous progress, less than 1% of applied nanosystems can hit their intended target location, such as a solid tumor, and this remains an obstacle to their full ability and potential with a high translational value. Therefore, achieving immune-tolerable, blood-compatible, and biofriendly nanoparticles remains an unmet need. The translational success of nanoformulations from bench to bedside involves a thorough assessment of their design, compatibility beyond cytotoxicity such as immune toxicity, blood compatibility, and immune-mediated destruction/rejection/clearance profile. Here, we report a one-pot process-engineered synthesis of ultrasmall gold nanoparticles (uGNPs) suitable for better body and renal clearance delivery of their payloads. We have obtained uGNP sizes of as low as 3 nm and have engineered the synthesis to allow them to be accurately sized (almost nanometer by nanometer). The synthesized uGNPs are biocompatible and can easily be functionalized to carry drugs, peptides, antibodies, and other therapeutic molecules. We have performed in vitro cell viability assays, immunotoxicity assays, inflammatory cytokine analysis, a complement activation study, and blood coagulation studies with the uGNPs to confirm their safety. These can help to set up a long-term safety-benefit framework of experimentation to reveal whether any designed nanoparticles are immune-tolerable and can be used as payload carriers for next-generation vaccines, chemotherapeutic drugs, and theranostic agents with better body clearance ability and deep tissue penetration."
    },
    {
      "Id": 7,
      "Year": 2021,
      "Authors": "J Das, N Idh, LIB Sikkeland, J Paues, M Lerm",
      "Title": "DNA methylome-based validation of induced sputum as an effective protocol to study lung immunity: construction of a classifier of pulmonary cell types",
      "Journal": "Epigenetics",
      "Number": "1-12",
      "Citation": 8,
      "DOI": "https://doi.org/10.1080/15592294.2021.1969499",
      "Abstract": "Flow cytometry is a classical approach used to define cell types in peripheral blood. While DNA methylation signatures have been extensively employed in recent years as an alternative to flow cytometry to define cell populations in peripheral blood, this approach has not been tested in lung-derived samples. Here, we compared bronchoalveolar lavage with a more cost-effective and less invasive technique based on sputum induction and developed a DNA methylome-based algorithm that can be used to deconvolute the cell types in such samples. We analysed the DNA methylome profiles of alveolar macrophages and lymphocytes cells isolated from the pulmonary compartment. The cells were isolated using two different methods, sputum induction and bronchoalveolar lavage. A strong positive correlation between the DNA methylome profiles of cells obtained with the two isolation methods was found. We observed the best correlation of the DNA methylomes when both isolation methods captured cells from the lower parts of the lungs. We also identified unique patterns of CpG methylation in DNA obtained from the two cell populations, which can be used as a signature to discriminate between the alveolar macrophages and lymphocytes by means of open-source algorithms. We validated our findings with external data and obtained results consistent with the previous findings. Our analysis opens up a new possibility to identify different cell populations from lung samples and promotes sputum induction as a tool to study immune cell populations from the lung."
    },
    {
      "Id": 10,
      "Year": 2021,
      "Authors": "J Das, N Idh, I Pehrson, J Paues, M Lerm",
      "Title": "A DNA methylome biosignature in alveolar macrophages from TB-exposed individuals predicts exposure to mycobacteria",
      "Journal": "medrxiv",
      "Number": "2021.03. 16.21253732",
      "Citation": 5,
      "DOI": "https://doi.org/10.1101/2021.03.16.21253732",
      "Abstract": "Several studies have identified biomarkers for tuberculosis (TB) diagnosis based on blood cell transcriptomics. Here, we instead studied epigenomics in the lung compartment by obtaining induced sputum from subjects included in a TB contact tracing. CD3- and HLA-DR-positive cells were isolated from the collected sputum and DNA methylome analyses performed. Unsupervised cluster analysis revealed that DNA methylomes of cells from TB-exposed individuals and controls appeared as separate clusters and the numerous genes that were differentially methylated were functionally connected. The enriched pathways were strongly correlated to data from published work on protective heterologous immunity to TB. Taken together, our results demonstrate that epigenetic changes related to trained immunity occurs in the pulmonary immune cells of TB-exposed individuals and that a DNA methylation signature can be derived from the DNA methylome. Such a signature can be further developed for clinical use as a marker of TB exposure."
    },
    {
      "Id": 13,
      "Year": 2021,
      "Authors": "S Kalsum, B Andersson, J Das, T Schön, M Lerm",
      "Title": "A high-throughput screening assay based on automated microscopy for monitoring antibiotic susceptibility of Mycobacterium tuberculosis phenotypes",
      "Journal": "BMC microbiology",
      "Number": "21 (1), 1-14",
      "Citation": 3,
      "DOI": "https://doi.org/10.1186/s12866-021-02212-3",
      "Abstract": "Efficient high-throughput drug screening assays are necessary to enable the discovery of new anti-mycobacterial drugs. The purpose of our work was to develop and validate an assay based on live-cell imaging which can monitor the growth of two distinct phenotypes of Mycobacterium tuberculosis and to test their susceptibility to commonly used TB drugs. Both planktonic and cording phenotypes were successfully monitored as fluorescent objects using the live-cell imaging system IncuCyte S3, allowing collection of data describing distinct characteristics of aggregate size and growth. The quantification of changes in total area of aggregates was used to define IC50 and MIC values of selected TB drugs which revealed that the cording phenotype grew more rapidly and displayed a higher susceptibility to rifampicin. In checkerboard approach, testing pair-wise combinations of sub-inhibitory concentrations of drugs, rifampicin, linezolid and pretomanid demonstrated superior growth inhibition of cording phenotype. Our results emphasize the efficiency of using automated live-cell imaging and its potential in high-throughput whole-cell screening to evaluate existing and search for novel antimycobacterial drugs."
    },
    {
      "Id": 16,
      "Year": 2021,
      "Authors": "I Pehrson, J Das, N Idh, L Karlsson, H Rylander, HH af Segerstad, E Reuterswärd, E Marttala, J Paues, M Méndez-Aranda, C Ugarte-Gil, M Lerm",
      "Title": "DNA methylomes derived from alveolar macrophages display distinct patterns in latent tuberculosis-implication for interferon gamma release assay status determination",
      "Journal": "MedRxiv",
      "Number": "2021.03. 16.21253725",
      "Citation": 2,
      "DOI": "https://doi.org/10.1101/2021.03.16.21253725",
      "Abstract": "Host innate immune cells, including alveolar macrophages, have been identified as key players in the early eradication of Mycobacterium tuberculosis and in the maintenance of an anti-mycobacterial immune memory, which is believed to be induced through epigenetic changes. The aim of the study was to elucidate whether exposure to M. tuberculosis induced a different DNA methylation pattern of alveolar macrophages and pulmonary T lymphocytes.Alveolar macrophages and T lymphocytes were isolated from induced sputum obtained from individuals living in Lima, which is an area high endemic for tuberculosis. To determine the latent tuberculosis infection status of the subjects, an interferon-γ release assay was performed. We evaluated the DNA methylomes of the alveolar macrophages and T lymphocytes using the Illumina Infinium Human Methylation 450K Bead Chip array, revealing a distinct DNA methylation pattern in alveolar macrophages allowing the discrimination of asymptomatic individuals with latent tuberculosis infection from non-infected individuals. Pathway analysis revealed that cell signalling of inflammation and chemokines in alveolar macrophages play a role in latent tuberculosis infection. In conclusion, we demonstrated that DNA methylation in alveolar macrophages can be used to determine the tuberculosis infection status of individuals in a high endemic setting."
    },
    {
      "Id": 30,
      "Year": 2021,
      "Authors": "I Pehrson, C Braian, L Karlsson, N Idh, EK Danielsson, B Andersson, J Paues, J Das, M Lerm",
      "Title": "DNA methylation profiling of immune cells from tuberculosis-exposed individuals overlaps with BCG-induced epigenetic changes and correlates with the emergence of anti-mycobacterial ‘corralling cells’",
      "Journal": "medRxiv",
      "Number": "2021.09. 01.21262945",
      "Citation": 0,
      "DOI": "https://doi.org/10.1101/2021.09.01.21262945",
      "Abstract": "The mechanism of protection of the only approved tuberculosis (TB) vaccine, Bacillus Calmette Guérin (BCG) is poorly understood. In recent years, epigenetic modifications induced by BCG have been demonstrated to reflect a state of trained immunity. The concept of trained immunity is now explored as a potential prevention strategy for a variety of infections. Studies on human TB immunity are dominated by those using peripheral blood as surrogate markers for immunity. Here, we instead studied the lung compartment by obtaining induced sputum from subjects included in a TB contact tracing. CD3- and HLA-DR-positive cells were isolated from the collected sputum and DNA methylome analyses performed. Unsupervised cluster analysis revealed that DNA methylomes of cells from TB-exposed individuals and controls appeared as separate clusters, and the numerous genes that were differentially methylated were functionally connected. The enriched pathways were strongly correlated to previously reported epigenetic changes and trained immunity in immune cells exposed to the BCG vaccine in human and animal studies. We further demonstrated that similar pathways were epigenetically modified in human macrophages trained with BCG in vitro. Finally, we found evidence of an M. tuberculosis-triggered emergence of a non-macrophage cell population from BCG-trained macrophage cultures. These cells did not phagocytose M. tuberculosis, but ‘corralled’ the bacteria into focal points, resulting in limitation of bacterial growth. Altogether, our study demonstrates that similar epigenetic changes are induced by M. tuberculosis and BCG and suggests that the modifications promote transformation of macrophages (or an unknown progenitor) to establish a yet undescribed cellular defense mechanism which we term ‘corralling’, based on the metaphorical resemblance to sheepdog herding."
    },
    {
      "Id": 3,
      "Year": 2019,
      "Authors": "J Das, D Verma, M Gustafsson, M Lerm",
      "Title": "Identification of DNA methylation patterns predisposing for an efficient response to BCG vaccination in healthy BCG-naïve subjects",
      "Journal": "Epigenetics",
      "Number": "14 (6), 589-601",
      "Citation": 34,
      "DOI": "https://doi.org/10.1080/15592294.2019.1603963",
      "Abstract": "The protection against tuberculosis induced by the Bacille Calmette Guérin (BCG) vaccine is unpredictable. In our previous study, altered DNA methylation pattern in peripheral blood mononuclear cells (PBMCs) in response to BCG was observed in a subgroup of individuals, whose macrophages killed mycobacteria effectively (‘responders’). These macrophages also showed production of Interleukin-1β (IL-1β) in response to mycobacterial stimuli before vaccination. Here, we hypothesized that the propensity to respond to the BCG vaccine is reflected in the DNA methylome. We mapped the differentially methylated genes (DMGs) in PBMCs isolated from responders/non-responders at the time point before vaccination aiming to identify possible predictors of BCG responsiveness. We identified 43 DMGs and subsequent bioinformatic analyses showed that these were enriched for actin-modulating pathways, predicting differences in phagocytosis. This could be validated by experiments showing that phagocytosis of mycobacteria, which is an event preceding mycobacteria-induced IL-1β production, was strongly correlated with the DMG pattern."
    },
    {
      "Id": 9,
      "Year": 2018,
      "Authors": "K Sen, D Bhattacharyya, A Sarkar, J Das, N Maji, M Basu, Z Ghosh, ...",
      "Title": "Exploring the major cross-talking edges of competitive endogenous RNA networks in human Chronic and Acute Myeloid Leukemia",
      "Journal": "Biochimica et Biophysica Acta (BBA)-General Subjects",
      "Number": "1862 (9), 1883-1892",
      "Citation": 6,
      "DOI": "https://doi.org/10.1016/j.bbagen.2018.06.002",
      "Abstract": "Human Chronic and Acute Myeloid Leukemia are myeloproliferative disorders in myeloid lineage of blood cells characterized by accumulation of aberrant white blood cells. In cancer, the anomalous transcriptome includes deregulated expression of non-coding RNAs in conjunction with protein-coding mRNAs in human genome. The coding or non-coding RNA transcripts harboring miRNA-binding sites can converse with and regulate each other by explicitly contending for a limited pool of shared miRNAs and act as competitive endogenous RNAs (ceRNAs). An unifying hypothesis attributing ‘modulation of expression of transcripts’ in this fashion had been defined as ‘competitive endogenous RNA hypothesis’. Network built with ceRNAs evidently offers a platform to elucidate complex regulatory interactions at post-transcriptional level in human cancers."
    },
    {
      "Id": 2,
      "Year": 2014,
      "Authors": "J Das, S Podder, TC Ghosh",
      "Title": "Insights into the miRNA regulations in human disease genes",
      "Journal": "BMC genomics",
      "Number": "15 (1), 1-7",
      "Citation": 44,
      "DOI": "https://doi.org/10.1186/1471-2164-15-1010",
      "Abstract": "MicroRNAs are a class of short non-coding RNAs derived from either cellular or viral transcripts that act post-transcriptionally to regulate mRNA stability and translation. In recent days, increasing numbers of miRNAs have been shown to be involved in the development and progression of a variety of diseases. We, therefore, intend to enumerate miRNA targets in several known disease classes to explore the degree of miRNA regulations on them which is unexplored till date. Here, we noticed that miRNA hits in cancer genes are remarkably higher than other diseases in human. Our observation suggests that UTRs and the transcript length of cancer related genes have a significant contribution in higher susceptibility to miRNA regulation. Moreover, gene duplication, mRNA stability, AREScores and evolutionary rate were likely to have implications for more miRNA targeting on cancer genes. Consequently, the regression analysis have confirmed that the AREScores plays most important role in detecting miRNA targets on disease genes. Interestingly, we observed that epigenetic modifications like CpG methylation and histone modification are less effective than miRNA regulations in controlling the gene expression of cancer genes. The intrinsic properties of cancer genes studied here, for higher miRNA targeting will enhance the knowledge on cancer gene regulation."
    },
    {
      "Id": 8,
      "Year": 2013,
      "Authors": "J Das, S Chakraborty, S Podder, TC Ghosh",
      "Title": "Complex-forming proteins escape the robust regulations of miRNA in human",
      "Journal": "FEBS letters",
      "Number": "587 (14), 2284-2287",
      "Citation": 8,
      "DOI": "https://doi.org/10.1016/j.febslet.2013.05.062",
      "Abstract": "Most proteins carry out their functions by participating in protein complexes. Recently, miRNAs were identified as promising post-transcriptional regulators that influence a large proportion of genes in higher eukaryotes. We aim to understand the role of miRNAs in the regulation of human proteins that are present in protein complexes. Here, we show that robust regulation by miRNA is absent in human complex-forming proteins. Moreover, the numbers of miRNA hits cannot direct the evolutionary fate of complex-forming proteins independently. However, the duplicated complex-forming proteins having a severe effect on organismal fitness are profoundly targeted by miRNA, probably to reduce the chances of dosage imbalance."
    },
    {
      "Id": 1,
      "Year": 2011,
      "Authors": "S Gupta, K Kumari, J Das, C Lata, S Puranik, M Prasad",
      "Title": "Development and utilization of novel intron length polymorphic markers in foxtail millet (Setaria italica (L.) P. Beauv.)",
      "Journal": "Genome",
      "Number": "54 (7), 586-602",
      "Citation": 59,
      "DOI": "https://doi.org/10.1139/g11-02",
      "Abstract": "Introns are noncoding sequences in a gene that are transcribed to precursor mRNA but spliced out during mRNA maturation and are abundant in eukaryotic genomes. The availability of codominant molecular markers and saturated genetic linkage maps have been limited in foxtail millet (Setaria italica (L.) P. Beauv.). Here, we describe the development of 98 novel intron length polymorphic (ILP) markers in foxtail millet using sequence information of the model plant rice. A total of 575 nonredundant expressed sequence tag (EST) sequences were obtained, of which 327 and 248 unique sequences were from dehydration- and salinity-stressed suppression subtractive hybridization libraries, respectively. The BLAST analysis of 98 EST sequences suggests a nearly defined function for about 64% of them, and they were grouped into 11 different functional categories. All 98 ILP primer pairs showed a high level of cross-species amplification in two millets and two nonmillets species ranging from 90% to 100%, with a mean of ∼97%. The mean observed heterozygosity and Nei’s average gene diversity 0.016 and 0.171, respectively, established the efficiency of the ILP markers for distinguishing the foxtail millet accessions. Based on 26 ILP markers, a reasonable dendrogram of 45 foxtail millet accessions was constructed, demonstrating the utility of ILP markers in germplasm characterizations and genomic relationships in millets and nonmillets species."
    }
  ];